# MLLAB-03 - NumPy

## Introduction

NumPy and SciPy are open-source add-on modules to Python. They provide common mathematical and numerical routines in pre-compiled, fast functions. The NumPy (Numeric Python) package provides basic routines for manipulating large arrays and matrices of numeric data. On the other hand, the SciPy (Scientific Python) package extends the functionality of NumPy with a substantial collection of useful algorithms (like minimization, Fourier transformation, regression, and other applied mathematical techniques). 

There are several ways to import NumPy. The standard approach is to use a simple `import` statement. To avoid writing `numpy.X` over and over again, it is common to import under the briefer name `np`.


In [1]:
import numpy
import numpy as np


## NumPy arrays

The central component of NumPy is its array object class. NumPy arrays are similar to the standard Python lists. Nevertheless, **every element in a NumPy array must be of the same data type**. Therefore, a NumPy array may store intrinsic numeric types like floats or integers, lists, tuples, other NumPy arrays and so on. NumPy arrays support operations with large amounts of numeric data very fast and are much more efficient than lists.

The function `array` takes two arguments: the list to be converted into the array and the type of each member of the list.


In [2]:
A = np.array([1, 4, 5, 8], float)
B = np.array([1, 4, 5, 8], int)
print("A =", A)
print(type(A))

print("\nB =", B)
print(type(B))


A = [1. 4. 5. 8.]
<class 'numpy.ndarray'>

B = [1 4 5 8]
<class 'numpy.ndarray'>


## Multi-dimensional arrays

NumPy also supports multi-dimensional arrays. This is performed by setting array elements to be other arrays. In contrast to the standard lists, the different axes are accessed using commas inside bracket notation.


In [3]:
# A two dimensional array: Each element of A is a Python list
A = np.array([[1, 2, 3], [4, 5, 6]], float)
print("A =\n", A)

print("\nA[0] =", A[0])   # The first element of A is the first list
print("A[1] =", A[1])   # The second element of A is the second list

print("\nA[0,0] =", A[0,0]) # Here is how we access individual array elements
print("A[0,1] =", A[0,1])


A =
 [[1. 2. 3.]
 [4. 5. 6.]]

A[0] = [1. 2. 3.]
A[1] = [4. 5. 6.]

A[0,0] = 1.0
A[0,1] = 2.0


## Indexing and slicing

Similarly to lists, the elements in NumPy arrays are zero-indexed: the first element gets an index equal to 1, the second element gets an index equal to 2, and so on.

Array slices also work similarly to lists. Therefore, the colon (`:`) operator means "select all elements" in the specified axis. On the other hand, the negative indices trigger a method that starts counting elements from the end of the specified axis.


In [4]:
# Examples on one-dimensional arrays
A = np.array([1, 4, 5, 8, 10, 14], float)

print("A =", A)

print("\nA[:2] =", A[:2])   # The first two elements of A (exclude the element with index 2)
print("A[1:3] =", A[1:3]) # The 2nd & the 3rd elements of A (include the element with index 1, exclude the one with index 3)
print("A[0] =", A[0], ",\nA[1] =", A[3])         # The first (index 0) and 4th (index 3) element of A

A[0] = 2                  # Insert 2 at the head of the array (i.e., replace 1)
A[len(A) - 1] = 100       # Insert 100 at the tail of the array (i.e., replace 14)
print("\nNew A =", A)


A = [ 1.  4.  5.  8. 10. 14.]

A[:2] = [1. 4.]
A[1:3] = [4. 5.]
A[0] = 1.0 ,
A[1] = 8.0

New A = [  2.   4.   5.   8.  10. 100.]


In [5]:
# Examples on two-dimensional arrays
A = np.array([[8, 2, 13, 4], [5, 16, 7, 18], [20, 6, 9, 12]], float)

print("A=\n", A)

print("\nA[1, :] - second row (index 1), all columns of A =", A[1, :])
print("A[:, 2] - all rows, third column (index 2) of A =", A[:, 2])
print("A[-1:,-2:] - last 1 row, last 2 columns of A =", A[-1:, -2:])


A=
 [[ 8.  2. 13.  4.]
 [ 5. 16.  7. 18.]
 [20.  6.  9. 12.]]

A[1, :] - second row (index 1), all columns of A = [ 5. 16.  7. 18.]
A[:, 2] - all rows, third column (index 2) of A = [13.  7.  9.]
A[-1:,-2:] - last 1 row, last 2 columns of A = [[ 9. 12.]]


## Useful array methods

NumPy provides a large number of useful operations and array transformations. A portion of them includes:

* `A.shape` returns a tuple with the dimensions of `A`.
* `A.reshape(shape)` rearranges the elements of `A` so that the new dimensions of `A` match `shape`. It will fail unless the elements fit exactly into the new dimensions.
* `A.ravel(order)` returns a contiguous flattened array. It is equivalent to `A.reshape(-1, order)`.
* `A.dtype` shows the type of values stored in `A`.
* `len(A)` returns the length of the first axis of `A`.
* `in` can be used to test if values are present in an array.
* Arrays can be reshaped by using tuples that specify new dimensions. This operation can be performed with `reshape` method.
* `A.copy()` creates a new, independent copy of `A`.
* `A.tolist()` converts a NumPy array `A` to a Python list.
* `A.fill(v)` fills an array `A` with a single value `v`.
* `transpose(A)` returns the transpose $A^T$ of an array $A$ - It is an equivalent expression to `A.T`.
* `flatten(A)` converts a multi-dimensional `A` array to one-dimensional.
* `arange(start, stop, step)` is similar to `range`, but it also stores the generated sequence into a NumPy array. More specifically, it returns evenly spaced numbers in the range `[start, stop]` over a specified interval `step`.
* `linspace(start, stop, num)` is similar to `arange`, but it returns `num` evenly spaced samples, calculated over the interval `[start, stop]`.
* `zeros(shape)` and `ones(shape)` create new arrays of specified dimensions `shape`, filled with 0's or 1's respectively.
* `identity(N)` creates a square identity matrix of a rank `N`.
* `eye(N, k)` returns square matrices or rank `N` with ones along the `k`-th diagonal.


In [6]:
A = np.array([[8, 2, 13, 4], [5, 16, 7, 18], [20, 6, 9, 12]], float)

print("Shape of A:", A.shape)

print("Type of A:", A.dtype)

print("Length of A:", len(A))

print("\n2 in A?", 2 in A)
print("0 in A?", 0 in A)


Shape of A: (3, 4)
Type of A: float64
Length of A: 3

2 in A? True
0 in A? False


In [7]:
# Array initialization with range
A = np.array(range(12), float) 
print("A =", A)

A = A.reshape((3, 4))   # Reshape A so that it has 3 rows and 4 columns
print("\nReshaped A =\n", A)

# Normal one-dimensional array initialization
A = np.array([1, 2, 3], float)

# This example demonstrates the difference between = and copy
B = A
C = A.copy()
A[0] = 0         # Change the first element of A. Notice that this change also affects B, but not C
print("\nA =", A)
print("B =", B)
print("C =", C)

# Convert NumPy array to a Python list
print("\nA as a list:", A.tolist())

# Fill all elements of A with zeroes
A.fill(0)
print("\nNew A with zeroes: ", A)


A = [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]

Reshaped A =
 [[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

A = [0. 2. 3.]
B = [0. 2. 3.]
C = [1. 2. 3.]

A as a list: [0.0, 2.0, 3.0]

New A with zeroes:  [0. 0. 0.]


In [8]:
A = np.array(range(6), float).reshape((2, 3))

print("A =\n", A)
print("\nA**T =\n", A.transpose())
print("\nA flattenned =\n", A.flatten())

# Create a NumPy array from a sequence (start, stop) and a given step
B = np.arange(2, 10, 0.5, dtype=float)
print("\nStarting from 2, go up to 10 by taking steps of 0.5\nB =", B)

# Create a NumPy array from a sequence (start, stop, step)
C = np.linspace(2, 10, 17, dtype=float)
print("\nStarting from 2, go up to 10 by constructing 17 numbers\nC =", C)

# Create a NumPy array of given dimensions and fill it with 1s
D = np.ones((2, 4), dtype=float)
print("\nA 2x4 array with ones\nD =\n", D)

# Create a NumPy array of given dimensions and fill it with 0s
E = np.zeros((2, 4), dtype=float)
print("\nA 2x4 array with zeros\nE =\n", E)

# Create a (square) identity matrix
I = np.identity(5, dtype=float)
print("\nAn identity matrix of rank 5\nI =\n", I)


A =
 [[0. 1. 2.]
 [3. 4. 5.]]

A**T =
 [[0. 3.]
 [1. 4.]
 [2. 5.]]

A flattenned =
 [0. 1. 2. 3. 4. 5.]

Starting from 2, go up to 10 by taking steps of 0.5
B = [2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]

Starting from 2, go up to 10 by constructing 17 numbers
C = [ 2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5  8.   8.5
  9.   9.5 10. ]

A 2x4 array with ones
D =
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]]

A 2x4 array with zeros
E =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]]

An identity matrix of rank 5
I =
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


## Array math

Basic mathematical functions operate element-wise on arrays, and are available both as operator overloads and as functions in the numpy module.

In addition to the standard operators, NumPy offers a large library of common mathematical functions that can be applied element-wise to arrays. Examples include `abs`, `sign`, `sqrt`, `log`, `log10`, `exp`, `sin`, `cos`, `tan`, `arcsin`, `arccos`, `arctan`, `sinh`, `cosh`, `tanh`, `arcsinh`, `arccosh`, `arctanh`, and so on.

Notice that the asterisk operator (`*`) performs element-wise multiplication between matrices (also known as Hadamard). This is different than the normal matrix multiplication that is performed by using the dot (`.`) operator. Apart from standard matrix multiplication, the dot operator can be used to compute the inner product between vectors, or to multiply a vector by a matrix.

Reminder: A matrix $A$ with $n$ rows and $k$ columns (i.e. dimensions $n \times k$) can only be multiplied by matrices $B$ with $k$ rows (i.e. dimensions $k \times m$). The product $C=A\dot{B}$ is a new matrix with dimensions $n \times m$.


In [9]:
A = np.array([[4, 6, 8], [7, 3, 5]], int)
B = np.array([[5, 2, 6], [1, 7, 4]], int)

print("A =\n", A)
print("B =\n", B)

print("\nAddition:\n", A + B)
print("OR:\n", np.add(A, B))

print("\nSubtraction:\n", A - B)
print("OR:\n", np.subtract(A, B))

print("\nElement-wise Multiplication:\n", A * B)
print("OR:\n", np.multiply(A, B))

print("\nDivision:\n", A / B)
print("OR:\n", np.divide(A, B))

print("\nelement-wise square root:")
SQR = np.sqrt(A)
print("SQR =\n", SQR)


A =
 [[4 6 8]
 [7 3 5]]
B =
 [[5 2 6]
 [1 7 4]]

Addition:
 [[ 9  8 14]
 [ 8 10  9]]
OR:
 [[ 9  8 14]
 [ 8 10  9]]

Subtraction:
 [[-1  4  2]
 [ 6 -4  1]]
OR:
 [[-1  4  2]
 [ 6 -4  1]]

Element-wise Multiplication:
 [[20 12 48]
 [ 7 21 20]]
OR:
 [[20 12 48]
 [ 7 21 20]]

Division:
 [[0.8        3.         1.33333333]
 [7.         0.42857143 1.25      ]]
OR:
 [[0.8        3.         1.33333333]
 [7.         0.42857143 1.25      ]]

element-wise square root:
SQR =
 [[2.         2.44948974 2.82842712]
 [2.64575131 1.73205081 2.23606798]]


In [10]:
# Two 2-dimensional arrays
A = np.array([[4, 6, 8], [7, 3, 5]], int)     # 2 rows, 3 columns
B = np.array([[2, 6], [1, 7], [4, 5]], int)   # 3 rows, 2 columns
print("A =\n", A)
print("B =\n", B)

v = np.array([20, 21, 22])  # a vector is equivalent to a 1-dimensional column array (3 rows, 1 column)
w = np.array([30, 31, 32])  # a vector is equivalent to a 1-dimensional column array

# Inner product of vectors
print("\nv.w =", v.dot(w))
print("OR v.w =", np.dot(v, w))

# Matrix / vector product; both produce the rank 1 array [29 67]
print("\nA.v =",A.dot(v))
print("OR A.v =", np.dot(A, v))

# Matrix / matrix product; both produce the rank 2 array
print(A.dot(B))
print(np.dot(A, B))


A =
 [[4 6 8]
 [7 3 5]]
B =
 [[2 6]
 [1 7]
 [4 5]]

v.w = 1955
OR v.w = 1955

A.v = [382 313]
OR A.v = [382 313]
[[ 46 106]
 [ 37  88]]
[[ 46 106]
 [ 37  88]]


## Array functions

NumPy also has a variety of array-wise functions that allow standard arithmetic operations and statistical processing of the array elements. The most representative functions include:

* `sum1`: returns the summation the array elements.
* `prod`: returns the products of the array elements.
* `mean`: returns the mean value of the array elements.
* `median`: returns the median value of the array elements.
* `var`: returns the variance of the array elements.
* `cov`: returns the co-variance of the array elements.
* `std`: returns the standard deviation of the array elements.
* `min`: returns the minimal element of the array.
* `max`: returns the maximal element of the array.
* `argmin`: returns the index of the minimal element of the array.
* `argmax`: returns the index of the maximal element of the array.


In [11]:
# Popular array-wise functions
A = np.array([2, 4, 3, 1, 1, 1], float)
print("A =", A)
print("\tSummation:\t", A.sum())
print("\tProduct:\t", A.prod())
print("\tMean Value:\t", A.mean())
print("\tMedian Value:\t", np.median(A))
print("\tVariance:\t", A.var())
print("\tCo-Variance:\t", np.cov(A))
print("\tStd Deviation:\t", A.std())
print("\tMinimum:\t", A.min())
print("\tMaximum:\t", A.max())
print("\targ Minimum:\t", A.argmin())
print("\targ Maximum:\t", A.argmax())

# Perform array-wise operations across an array axis (useful in multi-dimensional arrays)
A = np.array([[0, 2], [3, -1], [3, 5]], float)
print("\nA =\n", A)
print("\tMean-0:\t", A.mean(axis=0))
print("\tMean-1:\t", A.mean(axis=1))
print("\tMax-0:\t", A.mean(axis=0))
print("\tMax-1:\t", A.mean(axis=1))


A = [2. 4. 3. 1. 1. 1.]
	Summation:	 12.0
	Product:	 24.0
	Mean Value:	 2.0
	Median Value:	 1.5
	Variance:	 1.3333333333333333
	Co-Variance:	 1.6
	Std Deviation:	 1.1547005383792515
	Minimum:	 1.0
	Maximum:	 4.0
	arg Minimum:	 3
	arg Maximum:	 1

A =
 [[ 0.  2.]
 [ 3. -1.]
 [ 3.  5.]]
	Mean-0:	 [2. 2.]
	Mean-1:	 [1. 1. 4.]
	Max-0:	 [2. 2.]
	Max-1:	 [1. 1. 4.]


## Broadcasting

Broadcasting is an internal NumPy mechanism that enables arrays of different shapes to be used when performing arithmetic operations. Frequently we have a smaller array and a larger array, and we want to use the smaller array multiple times to perform some operation on the larger array. With broadcasting, the smaller array will be repeated as many times as necessary to perform the requested operation. 

In the following example, the one-dimensional array `B` was broadcast to a two-dimensional array that matched the size of `A`. In essence, `B` was reshaped and the empty elements were filled by repeating the pattern of the existing ones.


In [12]:
A = np.array([[1, 2], [3, 4], [5, 6]], float)
B = np.array([-1, 3], float)

# In this addition operation, B is silently extended (broadcasted) as follows:
# B = np.array([-1, 3], [-1, 3], [-1, 3], float)
print(A + B)


[[0. 5.]
 [2. 7.]
 [4. 9.]]


Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.
2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.
3. The arrays can be broadcast together if they are compatible in all dimensions.
4. After broadcasting, each array behaves as if it had shape equal to the element-wise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension.



## linalg: Linear Algebra sub-module

linalg is a NumPy sub-module that offers some very powerful mathematical tools. Examples include:

1. The determinant and the inverse of a matrix.
2. The computation of a matrix eigenvalues and eigenvectors. This operation is also known as eigen-decomposition and is frequently used in machine learning algorithms (e.g. spectral analysis algorithms like spectral clustering).
3. Singular Value Decomposition (SVD): This operation decomposes a $m \times n$ matrix $A$ into 3 lower rank matrices $U_{m \times m}$, $S_{m \times n}$, and $V_{n \times n}$, so that $A=USV^T$. SVD is a well-studied solution that is applied in multiple machine learning and data mining problems (clustering, classification, topic modelling, etc.).

All these operations (and numerous others) can be easily and efficiently computed with linalg.


In [13]:
# Compute the determinant of a matrix
A = np.array([[4, 2, 0], [9, 3, 7], [1, 2, 1]], float)
print ("\nDeterminant:", np.linalg.det(A))

# Compute the inverse of a matrix
B = np.linalg.inv(A)
print("\nB = Inverse of A:\n", B)
print("\nA.B =", np.dot(A, B))   # A.B = I

# Eigendecomposition
evals, evecs = np.linalg.eig(A)
print ("\nEigenvalues of A: ", evals)
print ("Eigenvectors of A:\n", evecs)

# Singular Value Decomposition
print("\n\n--- SVD --------------------------------------------------------------------------\n")
A = np.array([[1, 3, 4], [5, 2, 3]], float)
U, S, V = np.linalg.svd(A)

print("SVD: A =\n", A, "\nA shape: ", np.shape(A), "\n")
print("SVD: U =\n", U, "\nU shape: ", np.shape(U), "\n")
print("SVD: S =", S, " - S shape: ", np.shape(S), "\n")
print("SVD: V =\n", V, "\nV shape: ", np.shape(V), "\n")



Determinant: -48.00000000000003

B = Inverse of A:
 [[ 0.22916667  0.04166667 -0.29166667]
 [ 0.04166667 -0.08333333  0.58333333]
 [-0.3125      0.125       0.125     ]]

A.B = [[ 1.00000000e+00  0.00000000e+00 -2.22044605e-16]
 [ 0.00000000e+00  1.00000000e+00 -2.77555756e-17]
 [ 0.00000000e+00  0.00000000e+00  1.00000000e+00]]

Eigenvalues of A:  [ 8.85591316  1.9391628  -2.79507597]
Eigenvectors of A:
 [[-0.3663565  -0.54736745  0.25928158]
 [-0.88949768  0.5640176  -0.88091903]
 [-0.27308752  0.61828231  0.39592263]]


--- SVD --------------------------------------------------------------------------

SVD: A =
 [[1. 3. 4.]
 [5. 2. 3.]] 
A shape:  (2, 3) 

SVD: U =
 [[ 0.6113829  -0.79133492]
 [ 0.79133492  0.6113829 ]] 
U shape:  (2, 2) 

SVD: S = [7.46791327 2.86884495]  - S shape:  (2,) 

SVD: V =
 [[ 0.61169129  0.45753324  0.64536587]
 [ 0.78971838 -0.40129005 -0.46401635]
 [-0.046676   -0.79349205  0.60678804]] 
V shape:  (3, 3) 



## NumPy polynomials

NumPy also offers support for polynomials and has a special set of functions to perform math operations on polynomials. For instance:

* `poly` identifies a polynomial from its roots.
* `roots` finds the roots of a given polynomial.
* `polyval` evaluates a polynomial at a particular point.
* `polyfit` fits a polynomial of specified order to a set of data using a least-squares approach.


In [14]:
# Examples on polynomials
y = np.poly([-1, 1, 1, 10])  # these are the roots of the polynomial. NumPy will identify the polynomial that has these roots
print(y)

# Find the roots of a given polynomial
print(np.roots([1, 4, -2, 3]))         # x^3 + 4x^2 - 2x + 3 --> we are expecting 3 roots
print(np.polyval([1, 4, -2, 3], 4))    # Evaluate x^3 + 4x^2 - 2x + 3 at 4 = 4^3 + 4*4^2 - 2*4 + 3 = 64 + 64 - 8 + 3 = 123

x = [1, 2, 3, 4, 5, 6, 7, 8]
y = [0, 2, 1, 3, 7, 10, 11, 19]
print(np.polyfit(x, y, 1))


[  1. -11.   9.  11. -10.]
[-4.5797401 +0.j          0.28987005+0.75566815j  0.28987005-0.75566815j]
123
[ 2.48809524 -4.57142857]


## Random numbers

NumPy has built-in pseudorandom number generator routines in the sub-module random. The numbers are pseudorandom in the sense that they are generated deterministically from a seed number. However, they are distributed in what has statistical similarities to random fashion. NumPy uses a particular algorithm called the Mersenne Twister to generate pseudorandom numbers.

We can set the random number seed. The seed is an integer value. Any program that starts with the same seed will generate exactly the same sequence of random numbers each time it is run.

If this command is not run, NumPy automatically selects a random seed (based on the time) that is different every time a program runs.


In [15]:
np.random.seed(293423)
print(np.random.rand(5))
print(np.random.rand(2,3))
print(np.random.random())
print(np.random.randint(6, 10))

# Poisson distribution, λ = 6:
print(np.random.poisson(6.0))

# Gaussian distribution μ = 1.5, σ = 4.0
print(np.random.normal(1.5, 4.0))

# Standard normal distribution μ = 0, σ = 1
print(np.random.normal())


[0.33677247 0.52693437 0.79529578 0.78867702 0.02147624]
[[0.84612516 0.0704939  0.1526965 ]
 [0.77831701 0.80821151 0.82198398]]
0.9023965286127028
6
4
-1.4713023291989673
-0.2029724326424716
